In [2]:
!pip install scikit-learn
!pip install pandas
!pip install matplotlib
!pip install numpy
!pip install seaborn

Requirement already satisfied: scikit-learn in c:\users\valer\anaconda3\lib\site-packages (0.23.2)
Requirement already satisfied: scipy>=0.19.1 in c:\users\valer\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: numpy>=1.13.3 in c:\users\valer\anaconda3\lib\site-packages (from scikit-learn) (1.19.2)
Requirement already satisfied: joblib>=0.11 in c:\users\valer\anaconda3\lib\site-packages (from scikit-learn) (0.17.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\valer\anaconda3\lib\site-packages (from scikit-learn) (2.1.0)
Requirement already satisfied: pandas in c:\users\valer\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: pytz>=2017.2 in c:\users\valer\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\valer\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\valer\anaconda3\lib\site-packages (from pandas) (1.19.2)
Requirement already satisfied: six>=1.5 in c:\users\valer\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: matplotlib in c:\users\valer\anaconda3\lib\site-packages (3.3.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib) (8.0.1)
Requirement already satisfied: numpy>=1.15 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib) (1.19.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib) (2020.6.20)
Requirement already satisfied: cycler>=0.10 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: six in c:\users\valer\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib) (1.15.0)
Requirement already satisfied: numpy in c:\users\valer\anaconda3\lib\site-packages (1.19.2)
Requirement already satisfied: seaborn in c:\users\valer\anaconda3\lib\site-packages (0.11.0)
Requirement already satisfied: matplotlib>=2.2 in c:\users\valer\anaconda3\lib\site-packages (from seaborn) (3.3.2)
Requirement already satisfied: scipy>=1.0 in c:\users\valer\anaconda3\lib\site-packages (from seaborn) (1.5.2)
Requirement already satisfied: numpy>=1.15 in c:\users\valer\anaconda3\lib\site-packages (from seaborn) (1.19.2)
Requirement already satisfied: pandas>=0.23 in c:\users\valer\anaconda3\lib\site-packages (from seaborn) (1.1.3)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2020.6.20)
Requirement already satisfied: pillow>=6.2.0 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (8.0.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.3.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\valer\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\valer\anaconda3\lib\site-packages (from pandas>=0.23->seaborn) (2020.1)
Requirement already satisfied: six>=1.5 in c:\users\valer\anaconda3\lib\site-packages (from python-dateutil>=2.1->matplotlib>=2.2->seaborn) (1.15.0)

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df=pd.read_csv('Churn_Modelling.partial.csv', sep=',')
df.head()   #una stampa solo per conferma

,Exited,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0,9255,15601116,P'an,686,France,Male,32,6,0.00,2,1,1,179093.26
1,0,1562,15766374,Leak,632,Germany,Male,42,4,119624.60,2,1,1,195978.86
2,1,1671,15716994,Green,559,Spain,Male,24,3,114739.92,1,1,0,85891.02
3,1,6088,15730759,Chukwudi,561,France,Female,27,9,135637.00,1,1,0,153080.40
4,1,6670,15797900,Chinomso,517,France,Male,56,9,142147.32,1,0,0,39488.04

### Procedo ad eseguire lo split per il file di train e di test

In [5]:
from sklearn.model_selection import train_test_split

train,test = train_test_split(pd.read_csv('Churn_Modelling.partial.csv', sep=','), test_size=0.23, random_state=42) #Prendo il file iniziale perchè su df ci ho lavorato fino ad ora

train.to_csv('train.csv',index=False)
test.to_csv('test.csv',index=False)